version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: africashop
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  africashop-backend:
    image: africashop-backend:v1
    container_name: africashop-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/africashop
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    ports:
      - "8081:8080"
    depends_on:
      - mysql

volumes:
  mysql-data: